namespace Vortex.Core.Localization;

public class LocalizationEvent
{
    public const string LOCALIZATION_EVENT_LANGUAGE_CHANGED = "LOCALIZATION_EVENT_LANGUAGE_CHANGED";
    public const string LOCALIZATION_EVENT_LOCALIZATION_LOADED = "LOCALIZATION_EVENT_LOCALIZATION_LOADED";
    public const string LOCALIZATION_EVENT_LOCALIZATION_FAILED = "LOCALIZATION_EVENT_LOCALIZATION_FAILED";
}
